name: OarBecomesShovel
favicon: null
layout_spectrum: 0.73984
typography_spectrum: 0.40657
title: Oar Becomes Shovel
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.25
  lightness: 0.3754984852857888
  saturation: 0.5707487617619336
  rhythmicContrast: 0.23207918647676706
purpose: []
